<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Migrations\AbortMigrationException;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20200430132223 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws AbortMigrationException
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE mapseven_gpx_domain_model_gpx DROP FOREIGN KEY FK_E4F9A7C9BC26E2D6');
        $this->addSql('ALTER TABLE mapseven_gpx_domain_model_gpx ADD geojsonfile VARCHAR(40) DEFAULT NULL, DROP geojsoncompressed');
        $this->addSql('ALTER TABLE mapseven_gpx_domain_model_gpx ADD CONSTRAINT FK_E4F9A7C948AC587C FOREIGN KEY (geojsonfile) REFERENCES neos_media_domain_model_document (persistence_object_identifier)');
        $this->addSql('ALTER TABLE mapseven_gpx_domain_model_gpx ADD CONSTRAINT FK_E4F9A7C9BC26E2D6 FOREIGN KEY (gpxfile) REFERENCES neos_media_domain_model_document (persistence_object_identifier)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E4F9A7C948AC587C ON mapseven_gpx_domain_model_gpx (geojsonfile)');
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws AbortMigrationException
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE mapseven_gpx_domain_model_gpx DROP FOREIGN KEY FK_E4F9A7C948AC587C');
        $this->addSql('ALTER TABLE mapseven_gpx_domain_model_gpx DROP FOREIGN KEY FK_E4F9A7C9BC26E2D6');
        $this->addSql('DROP INDEX UNIQ_E4F9A7C948AC587C ON mapseven_gpx_domain_model_gpx');
        $this->addSql('ALTER TABLE mapseven_gpx_domain_model_gpx ADD geojsoncompressed VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, DROP geojsonfile');
        $this->addSql('ALTER TABLE mapseven_gpx_domain_model_gpx ADD CONSTRAINT FK_E4F9A7C9BC26E2D6 FOREIGN KEY (gpxfile) REFERENCES neos_media_domain_model_asset (persistence_object_identifier)');
    }
}