<?php

namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Migrations\AbortMigrationException;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20191210212015 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws AbortMigrationException
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql',
            'Migration can only be executed safely on "mysql".');

        $this->addSql('CREATE TABLE mapseven_gpx_domain_model_gpx (persistence_object_identifier VARCHAR(40) NOT NULL, gpxfile VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, date DATETIME NOT NULL, type VARCHAR(255) NOT NULL, active TINYINT(1) NOT NULL, author VARCHAR(255) DEFAULT NULL, startcoords JSON NOT NULL COMMENT \'(DC2Type:json_array)\', endcoords JSON NOT NULL COMMENT \'(DC2Type:json_array)\', distance DOUBLE PRECISION DEFAULT NULL, elapsedtime DOUBLE PRECISION DEFAULT NULL, totalelevationgain DOUBLE PRECISION DEFAULT NULL, elevhigh DOUBLE PRECISION DEFAULT NULL, elevlow DOUBLE PRECISION DEFAULT NULL, mincoords JSON NOT NULL COMMENT \'(DC2Type:json_array)\', maxcoords JSON NOT NULL COMMENT \'(DC2Type:json_array)\', startcity VARCHAR(255) DEFAULT NULL, startstate VARCHAR(255) DEFAULT NULL, startcountry VARCHAR(255) DEFAULT NULL, dtype VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_E4F9A7C9BC26E2D6 (gpxfile), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mapseven_gpx_domain_model_strava (persistence_object_identifier VARCHAR(40) NOT NULL, id BIGINT NOT NULL, movingtime DOUBLE PRECISION NOT NULL, averagespeed DOUBLE PRECISION NOT NULL, maxspeed DOUBLE PRECISION NOT NULL, polyline LONGTEXT DEFAULT NULL, summarypolyline LONGTEXT DEFAULT NULL, segmentefforts JSON NOT NULL COMMENT \'(DC2Type:json_array)\', photos JSON NOT NULL COMMENT \'(DC2Type:json_array)\', PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE mapseven_gpx_domain_model_gpx ADD CONSTRAINT FK_E4F9A7C9BC26E2D6 FOREIGN KEY (gpxfile) REFERENCES neos_media_domain_model_asset (persistence_object_identifier)');
        $this->addSql('ALTER TABLE mapseven_gpx_domain_model_strava ADD CONSTRAINT FK_4CA73C2F47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES mapseven_gpx_domain_model_gpx (persistence_object_identifier) ON DELETE CASCADE');
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws AbortMigrationException
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql',
            'Migration can only be executed safely on "mysql".');

        $this->addSql('ALTER TABLE mapseven_gpx_domain_model_strava DROP FOREIGN KEY FK_4CA73C2F47A46B0A');
        $this->addSql('DROP TABLE mapseven_gpx_domain_model_gpx');
        $this->addSql('DROP TABLE mapseven_gpx_domain_model_strava');
    }
}
