#                                                                        #
# Routes configuration                                                   #
#                                                                        #
# This file contains the configuration for the MVC router.               #
# Just add your own modifications as necessary.                          #
#                                                                        #
# Please refer to the Flow manual for possible configuration options.    #
# 

- name: 'Api Auth'
  uriPattern: 'auth'
  defaults:
    '@package': MapSeven.Gpx
    '@controller': Authentication
    '@action': auth
  httpMethods: ['POST']

- name: 'Api Auth'
  uriPattern: 'oauth2_callback'
  defaults:
    '@package': MapSeven.Gpx
    '@controller': Authentication
    '@action': oAuth2Callback
  httpMethods: ['GET']

- name: 'Api Strava Activities'
  uriPattern: 'api/v1/activities'
  defaults:
    '@package': MapSeven.Gpx
    '@controller': Strava

- name: 'Api Strava Activities'
  uriPattern: 'api/v1/activities/{strava.__identity}.json'
  defaults:
    '@package': MapSeven.Gpx
    '@controller': Strava
    '@action': showGeoJson
  httpMethods: ['GET']

- name: 'Api Strava Activities'
  uriPattern: 'api/v1/activities/{strava.__identity}.gpx'
  defaults:
    '@package': MapSeven.Gpx
    '@controller': Strava
    '@action': showGpx
  httpMethods: ['GET']

- name: 'Api Strava Activities'
  uriPattern: 'api/v1/activities/{strava.__identity}'
  defaults:
    '@package': MapSeven.Gpx
    '@controller': Strava

- name: 'Api Gpx Files'
  uriPattern: 'api/v1/files'
  defaults:
    '@package': MapSeven.Gpx
    '@controller': File

- name: 'Api Gpx Files'
  uriPattern: 'api/v1/files/{file.__identity}.json'
  defaults:
    '@package': MapSeven.Gpx
    '@controller': File
    '@action': showGeoJson
  httpMethods: ['GET']

- name: 'Api Gpx Files'
  uriPattern: 'api/v1/files/{file.__identity}.gpx'
  defaults:
    '@package': MapSeven.Gpx
    '@controller': File
    '@action': showGpx
  httpMethods: ['GET']

- name: 'Api Gpx Files'
  uriPattern: 'api/v1/files/{file.__identity}'
  defaults:
    '@package': MapSeven.Gpx
    '@controller': File