Neos:
  Flow:
    security:
      authentication:
        providers:
          TokenProvider:
            provider: \Neos\Flow\Security\Authentication\Provider\PersistedUsernamePasswordProvider
            token: 'Neos\Flow\Security\Authentication\Token\UsernamePasswordHttpBasic'

MapSeven:
  Gpx:
    domain: null
    strava:
      api:
        auth:
          client_id: null
          client_secret: null
          grant_type: refresh_token
          refresh_token: null
        base_uri: 'https://www.strava.com/api/v3/'
        oauth_uri: 'https://www.strava.com/oauth/token'
      mappingKeys:
        activity:
          - arrayAccess: author
            objectAccess: author
          - arrayAccess: average_speed
            objectAccess: averageSpeed
          - arrayAccess: distance
            objectAccess: distance
          - arrayAccess: elapsed_time
            objectAccess: elapsedTime
          - arrayAccess: elev_high
            objectAccess: elevHigh
          - arrayAccess: elev_low
            objectAccess: elevLow
          - arrayAccess: endLocation.address.city
            objectAccess: endCity
          - arrayAccess: endLocation.address.state
            objectAccess: endState
          - arrayAccess: endLocation.address.country
            objectAccess: endCountry
          - arrayAccess: end_latlng
            objectAccess: endCoords
          - arrayAccess: id
            objectAccess: id
          - arrayAccess: max_speed
            objectAccess: maxSpeed
          - arrayAccess: moving_time
            objectAccess: movingTime
          - arrayAccess: name
            objectAccess: name
          - arrayAccess: photos
            objectAccess: photos
          - arrayAccess: map.polyline
            objectAccess: polyline
          - arrayAccess: bounds.minLatLon
            objectAccess: minCoords
          - arrayAccess: bounds.maxLatLon
            objectAccess: maxCoords
          - arrayAccess: segment_efforts
            objectAccess: segmentEfforts
          - arrayAccess: startLocation.address.city
            objectAccess: startCity
          - arrayAccess: startLocation.address.state
            objectAccess: startState
          - arrayAccess: startLocation.address.country
            objectAccess: startCountry
          - arrayAccess: start_latlng
            objectAccess: startCoords
          - arrayAccess: map.summary_polyline
            objectAccess: summaryPolyline
          - arrayAccess: total_elevation_gain
            objectAccess: totalElevationGain
          - arrayAccess: total_elevation_loss
            objectAccess: totalElevationLoss
          - arrayAccess: type
            objectAccess: type
    geocoding:
      base_uri: https://eu1.locationiq.com/v1/
      key: null
    webhook:
      urls: []
    staticFile:
      create:
        enabled: false
        path: null
        extension: json
      commit:
        enabled: false
        path: null
    visualization:
      enabled: true
      api:
        basicAuth: null
        auth:
          refresh_token: null
          grant_type: refresh_token
        oauth_uri: https://api.ayvri.com/2.0/auth
        base_uri: https://api.ayvri.com/2.0/
    geoFunctions:
      api:
        base_uri: null
    mapbox:
      api:
        base_uri: https://api.mapbox.com/styles/v1/
        key: null
      staticImage:
        size: 640x480
        style: mapbox/satellite-streets-v11
        stroke: '#ff3300'
        strokeWidth: 5

t3n:
  GraphQL:
    endpoints:
      'graphql':
        schemas:
          root:
            typeDefs: 'resource://MapSeven.Gpx/Private/GraphQL/schema.root.graphql'
            resolvers:
              Query: 'MapSeven\Gpx\GraphQL\Resolver\QueryResolver'
              File: 'MapSeven\Gpx\GraphQL\Resolver\FileResolver'
              Strava: 'MapSeven\Gpx\GraphQL\Resolver\StravaResolver'
        schemaDirectives:
          auth: 't3n\GraphQL\Directive\AuthDirective'
          cached: 't3n\GraphQL\Directive\CachedDirective'
          cost: 't3n\GraphQL\Directive\CostDirective'
